language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lykaion/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lykaion/docker-react npm run test